version: '3.1'

services:
  db:
    image: postgres
    restart: always
    networks:
      - pg
    environment:
      POSTGRES_DB: piscineds
      POSTGRES_USER: alorain
      POSTGRES_PASSWORD: mysecretpassword

  adminer:
    image: dpage/pgadmin4
    restart: always
    networks:
      - pg
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: alorain@alorain.com
      PGADMIN_DEFAULT_PASSWORD: alorain
    volumes:
      - ./servers.json:/pgadmin4/servers.json

networks:
  pg:
